.TH ptreport 1 "2023-07-23" "Jamie Hardt" "User Manuals"
.SH NAME 
ptreport \- Pro Tools report generator
.SH SYNOPSIS
.SY ptreport
.\" .RI "[" "SOUND-FILE ..." "]"
.SH DESCRIPTION
.B ptreport
is a report generator for Pro Tools. It communicates with Pro Tools with PTSL,
reads clip names and times from the currently-open session and emits 
typesetting commands in the 
.BR groff "(1)"
language.
.SH OPTIONS
.I "ptreport supports no command-line options at this time."
.SH DETAILED DESCRIPTION
.I To be written
.SS MOTIVATION
.I To be written
.SS THEORY OF OPERATION
.I To be written 
.SH TRACK AND CLIP NAME CODES
.I To be written
.SH EXIT STATUS
.IP 0
On user quit.
.SH AUTHOR
Jamie Hardt <https://github.com/iluvcapra>
.SH BUGS
.SH SEE ALSO
.BR "groff" "(1),"
.BR "groff_ms" "(7)"
